FROM fedora:latest as base
RUN dnf -yqq install httpd
COPY myinfo.html /var/www/html/
EXPOSE 80
ENTRYPOINT /usr/sbin/httpd -DFOREGROUND



FROM base as website1
COPY website1.html /var/www/html/
FROM base as website2
COPY website2.html /var/www/html/
